blueprint:
  name: Свет, активируемый движением
  description: Включайте свет при обнаружении движения.
  domain: automation
  source_url: https://github.com/bieskholodov/Home-assistant/blob/main/motion_light.yaml
  author: bieskholodov
  input:
    motion_entity:
      name: Датчик движения
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    light_target:
      name: Свет
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Время ожидания
      description: Время оставить свет включенным после обнаружения последнего движения.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# Если движение обнаружено в течение задержки,
# мы перезапускаем скрипт.
mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

actions:
  - alias: "Включи свет"
    action: light.turn_on
    target: !input light_target
  - alias: "Подождите, пока устройство не прекратит движение."
    wait_for_trigger:
      trigger: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Подождите заданное количество секунд."
    delay: !input no_motion_wait
  - alias: "Выключите свет"
    action: light.turn_off
    target: !input light_target
